
services:
  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    environment:
      TYPESENSE_API_KEY: "48fe8dc-2d51-4e61-ba9f-057e835c0e77"
      TYPESENSE_DATA_DIR: "/data"
    restart: always
